// STEP 1
export const GET_USERS ="GET_USERS";
export const GET_PRODUCTS ="GET_PRODUCTS";
export const GET_PRODUCT_DETAILS =  "GET_PRODUCT_DETAILS"
export const GET_SELLER_DETAILS = "GET_SELLER_DETAILS"