# Generated by Django 3.2.8 on 2021-10-28 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_descripton', models.TextField(null=True)),
                ('item_main_image', models.ImageField(default='images/product/main.jpg', upload_to='images/product')),
                ('item_extra_image1', models.ImageField(default='images/product/extra1.jpg', null=True, upload_to='images/product')),
                ('item_extra_image2', models.ImageField(default='images/product/extra2.jpg', null=True, upload_to='images/product')),
                ('item_extra_image3', models.ImageField(default='images/product/extra3.jpg', null=True, upload_to='images/product')),
                ('item_extra_image4', models.ImageField(default='images/product/extra4.jpg', null=True, upload_to='images/product')),
            ],
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcounty_name', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jengabay.county')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_reg_no', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('town', models.CharField(max_length=50)),
                ('local_area_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('business_reg_doc', models.ImageField(default='images/profile/profile.jpg', upload_to='images/profile')),
                ('is_registered', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(default=datetime.datetime.now)),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jengabay.subcounty')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_placed', models.DateTimeField(default=datetime.datetime.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jengabay.buyer')),
                ('ordered_items', models.ManyToManyField(to='jengabay.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jengabay.seller'),
        ),
    ]
