# Generated by Django 3.2.8 on 2021-10-28 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jengabay', '0002_auto_20211028_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_placed',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
