# Generated by Django 3.2.8 on 2021-10-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jengabay', '0003_auto_20211028_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='profile_pic',
            field=models.ImageField(default='images/profile/profile.jpg', upload_to='images/profile'),
        ),
    ]
