# Generated by Django 3.2.9 on 2021-11-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jengabay', '0004_seller_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_descripton',
            new_name='item_description',
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('metal and steel work', 'Metal and Steel Work'), ('cement', 'Cement'), ('ceramics', 'Ceramics'), ('plastics', 'plastics'), ('wood and timber', 'Wood and Timber'), ('sand and stone', 'Sand and Stone'), ('bricks and masonry', 'Bricks and Masonry'), ('fabricators', 'Fabricators'), ('tools', 'Tools'), ('glass', 'Glass'), ('electrical systems', 'Electrical Systems'), ('paints', 'Paints'), ('plumbing', 'Plumbing'), ('security systems', 'Security Systems'), ('doors and windows', 'Doors and Windows'), ('telecommunications equipment', 'Telecomunications Equipment'), ('building safety', 'Building Safety'), ('furniture', 'Furniture'), ('surface finishing', 'Surface Finishing'), ('protection', 'Protection'), ('roofing', 'Roofing'), ('conveyor systems', 'Conveyor Systems'), ('composites', 'Composites'), ('flooring', 'Flooring'), ('adhesives', 'Adhesives'), ('others', 'Others')], default='uncategorized', max_length=50),
        ),
    ]
